name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Disable Password Complexity and Allow Blank Passwords
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item -Force C:\secpol.cfg -Confirm:$false
          
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force
          
          Write-Host "Disabled password complexity and enabled blank passwords"

      - name: Install RDP Wrapper for Multiple Sessions
        run: |
          Write-Host "Installing RDP Wrapper..."
          
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          $output = "$env:TEMP\RDPWrap.zip"
          
          try {
              Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
              Expand-Archive -Path $output -DestinationPath "$env:TEMP\RDPWrap" -Force
              
              cd "$env:TEMP\RDPWrap"
              cmd /c install.bat
              Start-Sleep -Seconds 5
              
              $iniUrl = "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini"
              $iniPath = "C:\Program Files\RDP Wrapper\rdpwrap.ini"
              Invoke-WebRequest -Uri $iniUrl -OutFile $iniPath -UseBasicParsing
              
              Restart-Service termservice -Force
              Write-Host "RDP Wrapper installed successfully!"
          }
          catch {
              Write-Warning "RDP Wrapper installation failed: $($_.Exception.Message)"
          }

      - name: Install Python and gdown
        run: |
          Write-Host "Installing Python..."
          choco install python -y --version=3.11.0
          
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          
          Write-Host "Installing gdown..."
          python -m pip install --upgrade pip
          pip install gdown
          
          Write-Host "Python and gdown installed!"

      - name: Download and Extract RAR from Google Drive
        run: |
          Write-Host "Downloading RAR from Google Drive..."
          
          $fileId = "1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP"
          $rarPath = "$env:TEMP\UserTemplate.rar"
          $extractPath = "$env:TEMP\UserTemplate"
          
          gdown $fileId -O $rarPath
          
          if (Test-Path $rarPath) {
              $fileSize = (Get-Item $rarPath).Length
              Write-Host "Downloaded: $([math]::Round($fileSize/1MB, 2)) MB"
              
              if ($fileSize -gt 10000) {
                  Write-Host "Installing 7-Zip..."
                  choco install 7zip -y
                  
                  New-Item -Path $extractPath -ItemType Directory -Force | Out-Null
                  Write-Host "Extracting RAR..."
                  & "C:\Program Files\7-Zip\7z.exe" x $rarPath -o"$extractPath" -y
                  
                  Write-Host "`nExtracted contents:"
                  Get-ChildItem -Path $extractPath | ForEach-Object {
                      Write-Host "  - $($_.Name)"
                  }
              }
          }

      - name: Overwrite Windows Default User Profile
        run: |
          Write-Host "Overwriting C:\Users\Default with custom template..."
          
          $extractPath = "$env:TEMP\UserTemplate"
          $defaultProfilePath = "C:\Users\Default"
          
          # Find Default folder
          $defaultFolder = Get-ChildItem -Path $extractPath -Directory -Filter "Default" -Recurse | Select-Object -First 1
          
          if ($defaultFolder) {
              $templatePath = $defaultFolder.FullName
              Write-Host "Found Default folder at: $templatePath"
          } else {
              $firstFolder = Get-ChildItem -Path $extractPath -Directory | Select-Object -First 1
              if ($firstFolder) {
                  $templatePath = $firstFolder.FullName
              } else {
                  $templatePath = $extractPath
              }
          }
          
          # Show contents
          Write-Host "`nContents inside template:"
          Get-ChildItem -Path $templatePath -Force | Select-Object -First 20 | ForEach-Object {
              Write-Host "  - $($_.Name)"
          }
          
          # Just overwrite everything - copy with Force will overwrite existing files
          Write-Host "`nCopying and overwriting to C:\Users\Default..."
          Copy-Item -Path "$templatePath\*" -Destination $defaultProfilePath -Recurse -Force -ErrorAction Continue
          
          Write-Host "`nC:\Users\Default overwritten successfully!"
          Write-Host "New users will get this custom profile on first login."

      - name: Create 10 Local Users
        run: |
          Write-Host "Creating 10 users..."
          
          for ($i = 1; $i -le 10; $i++) {
              $username = "User$i"
              net user $username /add /passwordreq:no /expires:never /active:yes
              net localgroup "Remote Desktop Users" $username /add
              net localgroup "Administrators" $username /add
              Write-Host "Created: $username"
          }
          
          Write-Host "`nAll users created!"

      - name: Grant Remote Desktop Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 10; $i++) {
                      $users += ",User$i"
                  }
                  $line = $line + $users
              }
              $newContent += $line
          }
          
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item -Force C:\secpol.cfg -Confirm:$false

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned"
              exit 1
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Verify RDP
        run: |
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "RDP failed"
              exit 1
          }

      - name: Maintain Connection
        run: |
          Write-Host "`n========================================="
          Write-Host "      RDP SERVER READY"
          Write-Host "========================================="
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User10"
          Write-Host "Password: NONE (blank)"
          Write-Host ""
          Write-Host "Custom Default profile installed!"
          Write-Host "========================================`n"
          
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active"
              Start-Sleep -Seconds 300
          }
