name: RDP

on:
  workflow_dispatch:

jobs:
  rdp-1:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y

      - name: Create User1 First
        run: |
          Write-Host "Creating User1..."
          net user User1 /add /passwordreq:no /expires:never /active:yes
          net localgroup "Remote Desktop Users" User1 /add
          net localgroup "Administrators" User1 /add

      - name: Install Software as User1
        run: |
          Write-Host "Installing software in User1 profile..."
          
          # Start jobs in parallel
          $jobs = @()
          
          # Brave installation job
          $jobs += Start-Job -ScriptBlock {
              $braveSetup = "C:\Users\User1\Downloads\BraveBrowserSetup-BRV002.exe"
              if (Test-Path $braveSetup) {
                  Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
              } else {
                  $braveSetup = "C:\Users\Public\Downloads\BraveBrowserSetup-BRV002.exe"
                  if (Test-Path $braveSetup) {
                      Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
                  } else {
                      Invoke-WebRequest -Uri "https://laptop-updates.brave.com/latest/winx64" -OutFile $braveSetup
                      Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
                  }
              }
              Write-Output "Brave installed"
          }
          
          # ExpressVPN installation job
          $jobs += Start-Job -ScriptBlock {
              $vpnSetup = "C:\Users\User1\Downloads\expressvpn_windows_12.104.0.128_release.exe"
              if (-not (Test-Path $vpnSetup)) {
                  $vpnUrl = "https://www.expressvpn.com/clients/windows/expressvpn_windows_12.104.0.128_release.exe"
                  Invoke-WebRequest -Uri $vpnUrl -OutFile $vpnSetup -UseBasicParsing
              }
              Start-Process -FilePath $vpnSetup -ArgumentList "/silent" -Wait
              Write-Output "ExpressVPN installed"
          }
          
          # Revo Uninstaller installation job
          $jobs += Start-Job -ScriptBlock {
              $revoSetup = "C:\Users\Revo Uninstaller Pro 5.3.5 Multilingual\RevoUninProSetup.exe"
              if (Test-Path $revoSetup) {
                  Start-Process -FilePath $revoSetup -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
                  Write-Output "Revo installed"
              }
          }
          
          # Wait for all installations to complete
          Write-Host "Installing Brave, ExpressVPN, and Revo in parallel..."
          $jobs | Wait-Job | Receive-Job
          $jobs | Remove-Job
          
          # Pin Brave to taskbar
          Start-Sleep -Seconds 5
          $bravePath = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
          if (Test-Path $bravePath) {
              $shell = New-Object -ComObject Shell.Application
              $folder = $shell.Namespace((Split-Path $bravePath))
              $item = $folder.ParseName((Split-Path $bravePath -Leaf))
              $item.InvokeVerb("taskbarpin")
              Write-Host "Brave pinned to taskbar"
          }
          
          Write-Host "All software installed!"

      - name: Create Remaining 299 Users
        run: |
          Write-Host "Creating remaining 299 users..."
          for ($i = 2; $i -le 300; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes 2>$null
              net localgroup "Remote Desktop Users" User$i /add 2>$null
              net localgroup "Administrators" User$i /add 2>$null
              if ($i % 25 -eq 0) { Write-Host "Created $i users..." }
          }
          Write-Host "All 300 users created!"

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 300; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp1-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 1 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User300"
          Write-Host "Password: NONE"
          Write-Host "Software: Brave, ExpressVPN, Revo"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }

  rdp-2:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y

      - name: Create User1 First
        run: |
          net user User1 /add /passwordreq:no /expires:never /active:yes
          net localgroup "Remote Desktop Users" User1 /add
          net localgroup "Administrators" User1 /add

      - name: Install Software as User1
        run: |
          $jobs = @()
          
          $jobs += Start-Job -ScriptBlock {
              $braveSetup = "C:\Users\User1\Downloads\BraveBrowserSetup-BRV002.exe"
              if (Test-Path $braveSetup) {
                  Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
              } else {
                  $braveSetup = "C:\Users\Public\Downloads\BraveBrowserSetup-BRV002.exe"
                  if (Test-Path $braveSetup) {
                      Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
                  } else {
                      Invoke-WebRequest -Uri "https://laptop-updates.brave.com/latest/winx64" -OutFile $braveSetup
                      Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
                  }
              }
          }
          
          $jobs += Start-Job -ScriptBlock {
              $vpnSetup = "C:\Users\User1\Downloads\expressvpn_windows_12.104.0.128_release.exe"
              if (-not (Test-Path $vpnSetup)) {
                  Invoke-WebRequest -Uri "https://www.expressvpn.com/clients/windows/expressvpn_windows_12.104.0.128_release.exe" -OutFile $vpnSetup -UseBasicParsing
              }
              Start-Process -FilePath $vpnSetup -ArgumentList "/silent" -Wait
          }
          
          $jobs += Start-Job -ScriptBlock {
              $revoSetup = "C:\Users\Revo Uninstaller Pro 5.3.5 Multilingual\RevoUninProSetup.exe"
              if (Test-Path $revoSetup) {
                  Start-Process -FilePath $revoSetup -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
              }
          }
          
          $jobs | Wait-Job | Receive-Job
          $jobs | Remove-Job
          
          Start-Sleep -Seconds 5
          $bravePath = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
          if (Test-Path $bravePath) {
              $shell = New-Object -ComObject Shell.Application
              $folder = $shell.Namespace((Split-Path $bravePath))
              $item = $folder.ParseName((Split-Path $bravePath -Leaf))
              $item.InvokeVerb("taskbarpin")
          }

      - name: Create Remaining 299 Users
        run: |
          for ($i = 2; $i -le 300; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes 2>$null
              net localgroup "Remote Desktop Users" User$i /add 2>$null
              net localgroup "Administrators" User$i /add 2>$null
              if ($i % 25 -eq 0) { Write-Host "Created $i users..." }
          }

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 300; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp2-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 2 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User300"
          Write-Host "Password: NONE"
          Write-Host "Software: Brave, ExpressVPN, Revo"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }
