      - name: Download User Template from Google Drive
        run: |
          Write-Host "Downloading user template ZIP from Google Drive..."
          
          $fileId = "1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP"
          $zipPath = "$env:TEMP\UserTemplate.zip"
          $extractPath = "$env:TEMP\UserTemplate"
          
          try {
              # Use curl (built-in Windows) for more reliable download
              $url = "https://drive.google.com/uc?export=download&id=$fileId"
              
              # Download the file
              curl -L -o $zipPath $url
              
              Write-Host "Downloaded ZIP file ($(Get-Item $zipPath).Length bytes)"
              
              # Extract using built-in Windows expand-archive with better error handling
              Add-Type -AssemblyName System.IO.Compression.FileSystem
              [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $extractPath)
              
              Write-Host "Extracted user template successfully"
              
              # List extracted contents
              Write-Host "`nExtracted contents:"
              Get-ChildItem -Path $extractPath -Recurse | Select-Object -First 30 | ForEach-Object { 
                  Write-Host "  $($_.FullName.Replace($extractPath, ''))"
              }
          }
          catch {
              Write-Error "Download/Extract failed: $($_.Exception.Message)"
              exit 1
          }
