name: RDP

on:
  workflow_dispatch:

jobs:
  rdp-1:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y

      - name: Create 300 Users
        run: |
          for ($i = 1; $i -le 300; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes 2>$null
              net localgroup "Remote Desktop Users" User$i /add 2>$null
              net localgroup "Administrators" User$i /add 2>$null
              if ($i % 25 -eq 0) { Write-Host "Created $i users..." }
          }

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 300; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Set Display Scaling to 400% for All Users
        run: |
          function Set-DpiScaling {
              param(
                  [string]$RegistryPath,
                  [int]$DpiValue = 384  # 384 DPI = 400% scaling (96 * 4)
              )
              try {
                  $desktopPath = Join-Path -Path $RegistryPath -ChildPath "Control Panel\Desktop"
                  $metricsPath = Join-Path -Path $desktopPath -ChildPath "WindowMetrics"
                  
                  if (Test-Path -Path $desktopPath) {
                      Set-ItemProperty -Path $desktopPath -Name "Win8DpiScaling" -Value 1 -Type DWord -Force -ErrorAction Stop
                      Set-ItemProperty -Path $desktopPath -Name "LogPixels" -Value $DpiValue -Type DWord -Force -ErrorAction Stop
                  }
                  if (Test-Path -Path $metricsPath) {
                      Set-ItemProperty -Path $metricsPath -Name "AppliedDPI" -Value $DpiValue -Type DWord -Force -ErrorAction Stop
                  }
                  Write-Host "Applied 400% DPI scaling to: $RegistryPath"
              }
              catch {
                  Write-Warning "Could not apply DPI settings to '$RegistryPath'. Error: $($_.Exception.Message)"
              }
          }
          
          $loadedSids = Get-ChildItem "Registry::HKEY_USERS" | Where-Object { $_.Name -like "*S-1-5-21-*" } | ForEach-Object { $_.PSChildName }
          foreach ($sid in $loadedSids) {
              $userHivePath = "Registry::HKEY_USERS\$sid"
              Set-DpiScaling -RegistryPath $userHivePath
          }
          
          reg load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT" 2>$null
          Set-DpiScaling -RegistryPath "Registry::HKEY_USERS\DefaultUser"
          reg unload "HKU\DefaultUser" 2>$null

      - name: Set Desktop Icon Size to Large for All Users
        run: |
          function Set-IconSize {
              param([string]$RegistryPath)
              try {
                  $shellBagsPath = Join-Path -Path $RegistryPath -ChildPath "Software\Microsoft\Windows\Shell\Bags\1\Desktop"
                  
                  if (-not (Test-Path $shellBagsPath)) {
                      New-Item -Path $shellBagsPath -Force | Out-Null
                  }
                  
                  Set-ItemProperty -Path $shellBagsPath -Name "IconSize" -Value 96 -Type DWord -Force
                  Write-Host "Applied large icon size to: $RegistryPath"
              }
              catch {
                  Write-Warning "Could not set icon size for '$RegistryPath'. Error: $($_.Exception.Message)"
              }
          }
          
          $loadedSids = Get-ChildItem "Registry::HKEY_USERS" | Where-Object { $_.Name -like "*S-1-5-21-*" } | ForEach-Object { $_.PSChildName }
          foreach ($sid in $loadedSids) {
              $userHivePath = "Registry::HKEY_USERS\$sid"
              Set-IconSize -RegistryPath $userHivePath
          }
          
          reg load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT" 2>$null
          Set-IconSize -RegistryPath "Registry::HKEY_USERS\DefaultUser"
          reg unload "HKU\DefaultUser" 2>$null

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp1-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 1 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User300"
          Write-Host "Password: NONE"
          Write-Host "Display: 400% scaling, Large icons"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }

  rdp-2:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y

      - name: Create 300 Users
        run: |
          for ($i = 1; $i -le 300; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes 2>$null
              net localgroup "Remote Desktop Users" User$i /add 2>$null
              net localgroup "Administrators" User$i /add 2>$null
              if ($i % 25 -eq 0) { Write-Host "Created $i users..." }
          }

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 300; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Set Display Scaling to 400% for All Users
        run: |
          function Set-DpiScaling {
              param(
                  [string]$RegistryPath,
                  [int]$DpiValue = 384  # 384 DPI = 400% scaling (96 * 4)
              )
              try {
                  $desktopPath = Join-Path -Path $RegistryPath -ChildPath "Control Panel\Desktop"
                  $metricsPath = Join-Path -Path $desktopPath -ChildPath "WindowMetrics"
                  
                  if (Test-Path -Path $desktopPath) {
                      Set-ItemProperty -Path $desktopPath -Name "Win8DpiScaling" -Value 1 -Type DWord -Force -ErrorAction Stop
                      Set-ItemProperty -Path $desktopPath -Name "LogPixels" -Value $DpiValue -Type DWord -Force -ErrorAction Stop
                  }
                  if (Test-Path -Path $metricsPath) {
                      Set-ItemProperty -Path $metricsPath -Name "AppliedDPI" -Value $DpiValue -Type DWord -Force -ErrorAction Stop
                  }
                  Write-Host "Applied 400% DPI scaling to: $RegistryPath"
              }
              catch {
                  Write-Warning "Could not apply DPI settings to '$RegistryPath'. Error: $($_.Exception.Message)"
              }
          }
          
          $loadedSids = Get-ChildItem "Registry::HKEY_USERS" | Where-Object { $_.Name -like "*S-1-5-21-*" } | ForEach-Object { $_.PSChildName }
          foreach ($sid in $loadedSids) {
              $userHivePath = "Registry::HKEY_USERS\$sid"
              Set-DpiScaling -RegistryPath $userHivePath
          }
          
          reg load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT" 2>$null
          Set-DpiScaling -RegistryPath "Registry::HKEY_USERS\DefaultUser"
          reg unload "HKU\DefaultUser" 2>$null

      - name: Set Desktop Icon Size to Large for All Users
        run: |
          function Set-IconSize {
              param([string]$RegistryPath)
              try {
                  $shellBagsPath = Join-Path -Path $RegistryPath -ChildPath "Software\Microsoft\Windows\Shell\Bags\1\Desktop"
                  
                  if (-not (Test-Path $shellBagsPath)) {
                      New-Item -Path $shellBagsPath -Force | Out-Null
                  }
                  
                  Set-ItemProperty -Path $shellBagsPath -Name "IconSize" -Value 96 -Type DWord -Force
                  Write-Host "Applied large icon size to: $RegistryPath"
              }
              catch {
                  Write-Warning "Could not set icon size for '$RegistryPath'. Error: $($_.Exception.Message)"
              }
          }
          
          $loadedSids = Get-ChildItem "Registry::HKEY_USERS" | Where-Object { $_.Name -like "*S-1-5-21-*" } | ForEach-Object { $_.PSChildName }
          foreach ($sid in $loadedSids) {
              $userHivePath = "Registry::HKEY_USERS\$sid"
              Set-IconSize -RegistryPath $userHivePath
          }
          
          reg load "HKU\DefaultUser" "C:\Users\Default\NTUSER.DAT" 2>$null
          Set-IconSize -RegistryPath "Registry::HKEY_USERS\DefaultUser"
          reg unload "HKU\DefaultUser" 2>$null

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp2-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 2 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User300"
          Write-Host "Password: NONE"
          Write-Host "Display: 400% scaling, Large icons"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }
