name: RDP-TEST

on:
  workflow_dispatch:

jobs:
  test-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service TermService -Force

      - name: Set Resolution to 1920x1080
        run: |
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxXResolution" -Value 1920
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "MaxYResolution" -Value 1080

      - name: Allow Blank Password
        run: |
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Create 1 User
        run: |
          net user TestUser /add /passwordreq:no /active:yes
          net localgroup "Remote Desktop Users" TestUser /add
          net localgroup "Administrators" TestUser /add

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\ts.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "$env:TEMP\ts.msi", "/quiet" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=test-rdp
          Start-Sleep -Seconds 10
          $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          Write-Host "RDP READY: $ip | User: TestUser | Pass: BLANK"
          echo "TAILSCALE_IP=$ip" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          while ($true) { Start-Sleep 300 }
