name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Disable Password Complexity and Allow Blank Passwords
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item -Force C:\secpol.cfg -Confirm:$false
          
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force
          
          Write-Host "Disabled password complexity and enabled blank passwords"

      - name: Install RDP Wrapper for Multiple Sessions
        run: |
          Write-Host "Installing RDP Wrapper to enable multiple RDP sessions..."
          
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          $output = "$env:TEMP\RDPWrap.zip"
          
          try {
              Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
              Expand-Archive -Path $output -DestinationPath "$env:TEMP\RDPWrap" -Force
              
              cd "$env:TEMP\RDPWrap"
              cmd /c install.bat
              Start-Sleep -Seconds 5
              
              $iniUrl = "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini"
              $iniPath = "C:\Program Files\RDP Wrapper\rdpwrap.ini"
              Invoke-WebRequest -Uri $iniUrl -OutFile $iniPath -UseBasicParsing
              
              Restart-Service termservice -Force
              Write-Host "RDP Wrapper installed successfully!"
          }
          catch {
              Write-Warning "RDP Wrapper installation failed: $($_.Exception.Message)"
          }

      - name: Install Python and gdown for Google Drive Download
        run: |
          Write-Host "Installing Python..."
          choco install python -y --version=3.11.0
          
          # Refresh PATH
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          
          Write-Host "Installing gdown..."
          python -m pip install --upgrade pip
          pip install gdown
          
          Write-Host "Python and gdown installed!"

      - name: Download and Extract RAR from Google Drive
        run: |
          Write-Host "Downloading RAR from Google Drive using gdown..."
          
          $fileId = "1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP"
          $rarPath = "$env:TEMP\UserTemplate.rar"
          $extractPath = "$env:TEMP\UserTemplate"
          
          # Download using gdown
          gdown $fileId -O $rarPath
          
          # Check if download was successful
          if (Test-Path $rarPath) {
              $fileSize = (Get-Item $rarPath).Length
              Write-Host "Downloaded file size: $fileSize bytes ($([math]::Round($fileSize/1MB, 2)) MB)"
              
              if ($fileSize -gt 10000) {
                  # Install 7-Zip
                  Write-Host "Installing 7-Zip..."
                  choco install 7zip -y
                  
                  # Extract RAR
                  New-Item -Path $extractPath -ItemType Directory -Force | Out-Null
                  Write-Host "Extracting RAR..."
                  & "C:\Program Files\7-Zip\7z.exe" x $rarPath -o"$extractPath" -y
                  
                  Write-Host "`nExtracted contents:"
                  Get-ChildItem -Path $extractPath | ForEach-Object {
                      Write-Host "  - $($_.Name)"
                  }
              }
              else {
                  Write-Warning "File too small, creating basic structure..."
                  New-Item -Path $extractPath -ItemType Directory -Force | Out-Null
                  $folders = @("AppData", "Desktop", "Documents", "Downloads", "Music", "Pictures", "Videos", "Contacts", "Links", "Saved Games", "Searches", "Favorites")
                  foreach ($folder in $folders) {
                      New-Item -Path "$extractPath\$folder" -ItemType Directory -Force | Out-Null
                  }
              }
          }
          else {
              Write-Warning "Download failed, creating basic structure..."
              New-Item -Path $extractPath -ItemType Directory -Force | Out-Null
              $folders = @("AppData", "Desktop", "Documents", "Downloads", "Music", "Pictures", "Videos", "Contacts", "Links", "Saved Games", "Searches", "Favorites")
              foreach ($folder in $folders) {
                  New-Item -Path "$extractPath\$folder" -ItemType Directory -Force | Out-Null
              }
          }

      - name: Create 10 Local Users with No Password
        run: |
          Write-Host "Creating 10 local users..."
          
          for ($i = 1; $i -le 10; $i++) {
              $username = "User$i"
              
              try {
                  net user $username /add /passwordreq:no /expires:never /active:yes
                  net localgroup "Remote Desktop Users" $username /add
                  net localgroup "Administrators" $username /add
                  
                  Write-Host "Created user: $username"
              }
              catch {
                  Write-Warning "Failed to create $username"
              }
          }
          
          Write-Host "All 10 users created successfully!"

      - name: Create User Profiles and Apply Custom Template
        run: |
          Write-Host "Creating user profiles and applying custom template..."
          
          $extractPath = "$env:TEMP\UserTemplate"
          $usersPath = "C:\Users"
          
          # Find the actual template folder
          $templateFolder = Get-ChildItem -Path $extractPath -Directory | Select-Object -First 1
          if ($templateFolder) {
              $templatePath = $templateFolder.FullName
              Write-Host "Using template from: $templatePath"
          } else {
              $templatePath = $extractPath
              Write-Host "Using template from: $templatePath"
          }
          
          # Show what will be copied
          Write-Host "`nTemplate contents to copy:"
          Get-ChildItem -Path $templatePath -Force | ForEach-Object {
              if ($_.PSIsContainer) {
                  Write-Host "  - $($_.Name) [Folder]"
              } else {
                  Write-Host "  - $($_.Name) [File - $($_.Length) bytes]"
              }
          }
          
          for ($i = 1; $i -le 10; $i++) {
              $username = "User$i"
              $userProfilePath = "$usersPath\$username"
              
              Write-Host "`n--- Setting up $username ---"
              
              try {
                  # Create user profile directory
                  New-Item -Path $userProfilePath -ItemType Directory -Force | Out-Null
                  Write-Host "Created profile folder: $userProfilePath"
                  
                  # Copy all folders from template
                  Get-ChildItem -Path $templatePath -Directory -Force | ForEach-Object {
                      $destFolder = Join-Path $userProfilePath $_.Name
                      try {
                          Copy-Item -Path $_.FullName -Destination $destFolder -Recurse -Force -ErrorAction Continue
                          Write-Host "  Copied folder: $($_.Name)"
                      }
                      catch {
                          Write-Warning "  Failed to copy folder $($_.Name)"
                      }
                  }
                  
                  # Copy all files from template (like ntuser.dat)
                  Get-ChildItem -Path $templatePath -File -Force | ForEach-Object {
                      try {
                          Copy-Item -Path $_.FullName -Destination $userProfilePath -Force -ErrorAction Continue
                          Write-Host "  Copied file: $($_.Name)"
                      }
                      catch {
                          Write-Warning "  Failed to copy file $($_.Name)"
                      }
                  }
                  
                  # Set permissions
                  icacls $userProfilePath /grant "${username}:(OI)(CI)F" /T /C /Q | Out-Null
                  Write-Host "  Set permissions for $username"
                  
                  $itemCount = (Get-ChildItem -Path $userProfilePath -Force | Measure-Object).Count
                  Write-Host "  Total items: $itemCount"
                  
              }
              catch {
                  Write-Error "Failed to setup $username"
              }
          }
          
          Write-Host "`n=== All user profiles created ==="

      - name: Grant Remote Desktop Logon Rights
        run: |
          Write-Host "Granting Remote Desktop logon rights..."
          
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 10; $i++) {
                      $users += ",User$i"
                  }
                  $line = $line + $users
              }
              $newContent += $line
          }
          
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item -Force C:\secpol.cfg -Confirm:$false

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned"
              exit 1
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Verify RDP
        run: |
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "RDP failed"
              exit 1
          }

      - name: Maintain Connection
        run: |
          Write-Host "`n========================================="
          Write-Host "      RDP SERVER READY"
          Write-Host "========================================="
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User10"
          Write-Host "Password: NONE (blank)"
          Write-Host "Custom profiles from Google Drive RAR!"
          Write-Host "========================================`n"
          
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active"
              Start-Sleep -Seconds 300
          }
