name: RDP

on:
  workflow_dispatch:

jobs:
  rdp-1:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          Write-Host "Installing tools..."
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          Write-Host "`nDownloading RAR 1 (Default.rar)..."
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          
          Write-Host "Downloading RAR 2..."
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          Write-Host "`nExtracting RAR 1 to C:\Users..."
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          
          Write-Host "Extracting RAR 2 to C:\Users..."
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y
          
          Write-Host "`nBoth RARs extracted to C:\Users"

      - name: Install Brave Browser and ExpressVPN
        run: |
          Write-Host "Installing Brave Browser..."
          
          # Install Brave from the setup file in Downloads
          $braveSetup = "C:\Users\Public\Downloads\BraveBrowserSetup-BRV002.exe"
          if (Test-Path $braveSetup) {
              Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
              Write-Host "Brave installed"
          } else {
              Write-Host "Brave setup not found, downloading..."
              Invoke-WebRequest -Uri "https://laptop-updates.brave.com/latest/winx64" -OutFile $braveSetup
              Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
          }
          
          # Pin Brave to taskbar
          $bravePath = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
          if (Test-Path $bravePath) {
              $shell = New-Object -ComObject Shell.Application
              $folder = $shell.Namespace((Split-Path $bravePath))
              $item = $folder.ParseName((Split-Path $bravePath -Leaf))
              $item.InvokeVerb("taskbarpin")
              Write-Host "Brave pinned to taskbar"
          }
          
          Write-Host "`nDownloading and installing ExpressVPN..."
          $vpnUrl = "https://www.expressvpn.com/clients/windows/expressvpn_windows_12.104.0.128_release.exe"
          $vpnSetup = "C:\Users\Public\Downloads\expressvpn.exe"
          Invoke-WebRequest -Uri $vpnUrl -OutFile $vpnSetup -UseBasicParsing
          Start-Process -FilePath $vpnSetup -ArgumentList "/silent" -Wait
          Write-Host "ExpressVPN installed"
          
          Write-Host "`nInstalling Revo Uninstaller..."
          $revoSetup = "C:\Users\Revo Uninstaller Pro 5.3.5 Multilingual\RevoUninProSetup.exe"
          if (Test-Path $revoSetup) {
              Start-Process -FilePath $revoSetup -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
              Write-Host "Revo Uninstaller installed"
          }
          
          Write-Host "`nAll software installed!"

      - name: Create 30 Users
        run: |
          for ($i = 1; $i -le 30; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes
              net localgroup "Remote Desktop Users" User$i /add
              net localgroup "Administrators" User$i /add
              Write-Host "Created User$i"
          }

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 30; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp1-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 1 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User30"
          Write-Host "Password: NONE"
          Write-Host "Software installed:"
          Write-Host "  - Brave Browser (pinned)"
          Write-Host "  - ExpressVPN"
          Write-Host "  - Revo Uninstaller"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }

  rdp-2:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Disable Password Requirements
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 0") | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          Remove-Item C:\secpol.cfg -Force
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name "LimitBlankPasswordUse" -Value 0 -Force

      - name: Install RDP Wrapper
        run: |
          $url = "https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:TEMP\RDPWrap.zip" -UseBasicParsing
          Expand-Archive -Path "$env:TEMP\RDPWrap.zip" -DestinationPath "$env:TEMP\RDPWrap" -Force
          cd "$env:TEMP\RDPWrap"
          cmd /c install.bat
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini" -OutFile "C:\Program Files\RDP Wrapper\rdpwrap.ini" -UseBasicParsing
          Restart-Service termservice -Force

      - name: Download and Extract Both RARs
        run: |
          choco install python 7zip -y
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pip install gdown
          
          gdown 1uw9Z-0XJWuQHZAXuGNKtPD6322V7r0iP -O "$env:TEMP\rar1.rar"
          gdown 1ZWucKt1fkguhHMhTN7KbuETtKCpeXWKc -O "$env:TEMP\rar2.rar"
          
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar1.rar" -o"C:\Users" -y
          & "C:\Program Files\7-Zip\7z.exe" x "$env:TEMP\rar2.rar" -o"C:\Users" -y

      - name: Install Brave Browser and ExpressVPN
        run: |
          $braveSetup = "C:\Users\Public\Downloads\BraveBrowserSetup-BRV002.exe"
          if (Test-Path $braveSetup) {
              Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
          } else {
              Invoke-WebRequest -Uri "https://laptop-updates.brave.com/latest/winx64" -OutFile $braveSetup
              Start-Process -FilePath $braveSetup -ArgumentList "/silent /install" -Wait
          }
          
          $bravePath = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
          if (Test-Path $bravePath) {
              $shell = New-Object -ComObject Shell.Application
              $folder = $shell.Namespace((Split-Path $bravePath))
              $item = $folder.ParseName((Split-Path $bravePath -Leaf))
              $item.InvokeVerb("taskbarpin")
          }
          
          $vpnUrl = "https://www.expressvpn.com/clients/windows/expressvpn_windows_12.104.0.128_release.exe"
          $vpnSetup = "C:\Users\Public\Downloads\expressvpn.exe"
          Invoke-WebRequest -Uri $vpnUrl -OutFile $vpnSetup -UseBasicParsing
          Start-Process -FilePath $vpnSetup -ArgumentList "/silent" -Wait
          
          $revoSetup = "C:\Users\Revo Uninstaller Pro 5.3.5 Multilingual\RevoUninProSetup.exe"
          if (Test-Path $revoSetup) {
              Start-Process -FilePath $revoSetup -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
          }

      - name: Create 30 Users
        run: |
          for ($i = 1; $i -le 30; $i++) {
              net user User$i /add /passwordreq:no /expires:never /active:yes
              net localgroup "Remote Desktop Users" User$i /add
              net localgroup "Administrators" User$i /add
          }

      - name: Grant RDP Rights
        run: |
          secedit /export /cfg C:\secpol.cfg
          $content = Get-Content C:\secpol.cfg
          $newContent = @()
          foreach ($line in $content) {
              if ($line -like "SeRemoteInteractiveLogonRight*") {
                  $users = ""
                  for ($i = 1; $i -le 30; $i++) { $users += ",User$i" }
                  $line = $line + $users
              }
              $newContent += $line
          }
          $newContent | Out-File C:\secpol.cfg
          secedit /configure /db c:\windows\security\local.sdb /cfg C:\secpol.cfg /areas USER_RIGHTS
          Remove-Item C:\secpol.cfg -Force

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "$env:TEMP\tailscale.msi"
          Start-Process msiexec.exe -ArgumentList "/i", "`"$env:TEMP\tailscale.msi`"", "/quiet", "/norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp2-$env:GITHUB_RUN_ID
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Keep Alive
        run: |
          Write-Host "========================================="
          Write-Host "RDP 2 READY"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "Users: User1-User30"
          Write-Host "Password: NONE"
          Write-Host "Software installed:"
          Write-Host "  - Brave Browser (pinned)"
          Write-Host "  - ExpressVPN"
          Write-Host "  - Revo Uninstaller"
          Write-Host "========================================="
          
          while ($true) { Start-Sleep -Seconds 300 }
